# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
      
    - name: Install dependencies
      run: |
        go version
        go mod download

    - name: Build server
      run: |
        cd server
        go build -v .

    - name: Build client
      run: |
        cd client
        go build -v .

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          ./client/client.exe
          ./server/server.exe